### ISSUE TITLE
关于Pro V3 V4

### ISSUE THREAD

**Issue by xiaohuoni** [xiaohuoni/ant-design-kit#18]
就我个人喜好而言，还是比较喜欢约定式的，无路由配置的协同工作方式。
完全依赖umi的特性，应该可以让pro变得足够灵活，所以我依旧坚持保留v3（那个pro不存在的版本）
# V3
1、约定式路由
2、TypeScript
3、保留Pages文件
4、预计Init过程->clone->delete pages->add init page-dev
5、i18n mock 根据国际化配置，加载不同的mock文件
6、开发环境，自定义皮肤方案，umi ui、umi插件、或者前端调试工具
# V4
1、将页面转换为块 umi-blocks
2、使i18n可选择 umi-plugin-locale
3、黑暗的主题 SettingDrawer
4、更多自定义设置 defaultSettings
5、更好的组件 ？？
6、TypeScript
7、cli工具 ant-design-pro-cli
## blocks 功能
根据何乐同学的猜测（没在官方看到对这个的详细说明）
> 可能 antd pro 希望每个 block 足够独立，不仅可以用在 antd pro 基础的项目，还可以用在其他所有 umi 基础的项目
> block 里用到的所有 umi 特性都需要可配置，比如有些基于 umi 的项目想要引入 pro 的 block ，但是并没有开启 locale ，pro 的 cli 可以去掉 block 里对应的内容

# 开发计划
1、依旧保持在v3分支上，处理ts。
2、v3基本完成之后，以step by step的方式通过一个Issues对应一个PR的方式，同步部分代码到ant-design-kit，便于初学者阅读源码。可以在相应的Issues和PR上评论提问。持续维护答疑。当作一个公开的学习笔记。
3、等v4和master同步之后，有选择性的同步到v4。

**Comment by afc163** [comment]
除了约定式路由，其余的也都是 v4 需要的功能。

cli 工具可以直接作为 umi 本身的功能来做。

---

其他没啥问题，我初衷是希望 @xiaohuoni 的改动都能落回主库，这样能造福社区更多的人。
