### ISSUE TITLE
Pro V3 Record

### ISSUE THREAD

**Issue by xiaohuoni** [xiaohuoni/ant-design-kit#19]
# Transform TypeScript
2019-03-10 pages done --- 2019-03-07
2019-03-15 components done 
2019-03-18 fix bug and Transform TypeScript done
## global
* [x] app.js
* [x]  global.js
* [x] typings.d.ts
<del>service-worker.js</del> 
## components
* [x] - ActiveChart
* [x] -  ArticleListContent
* [x] - Authorized https://github.com/ant-design/ant-design-pro/pull/3771
* [x]  AvatarList
* [x]  Charts
* [x] -- AsyncLoadBizCharts.tsx
* [x] -- Bar
* [x] --  ChartCard
* [x] --  Field
* [x] --  Gauge
* [x] --  MiniArea
* [x] --  MiniBar
* [x] --  MiniProgress
* [x] --  Pie
* [x] --  Radar
* [x] --  TagCloud
* [x] -- TimelineChart
* [x] --  WaterWave
* [x] --  autoHeight.js
* [x] --  bizcharts.js
* [x] --  index.js
* [x]  CountDown
* [x]  DescriptionList
* [x] ---  Description.js
* [x] ---  DescriptionList.js
* [x] --  index.js
* [x] --  responsive.js
* [x]  EditableItem
* [x]  EditableLinkGroup
* [x]  Ellipsis
* [x]  Exception
* [x]  FooterToolbar
* [x]  GlobalFooter
* [x]  GlobalHeader
* [x]  HeaderDropdown
* [x]  HeaderSearch
* [x]  IconFont
* [x]  Login
* [x]  NoticeIcon
* [x]  NumberInfo
* [x]  PageHeader
* [x]  PageHeaderWrapper
* [x]  PageLoading
* [x]  Result
* [x]  SelectLang
* [x]  SettingDrawer
* [x]  SiderMenu
* [x]  StandardFormRow
* [x]  StandardTable
* [x]  TagSelect
* [x]  TopNavHeader
* [x] Trend

##  layouts
* [x]  BasicLayout.tsx
* [x]   BlankLayout.tsx
* [x]  Footer.tsx
* [x]  Header.tsx
* [x]  MenuContext.tsx
* [x]   UserLayout.tsx

## locales
* [x]  All 

## models
* [x]  global.ts
* [x]   list.ts
* [x]   login.ts
* [x]   menu.ts
* [x]   project.ts
* [x]   setting.ts
* [x]   user.ts

## pages
* [x]   404.tsx
* [x]  Account
* [x] -- Center
* [x] -- Settings
* [x] --- BaseView.js
* [x] --- BindingView.js
* [x] --- GeographicView.js
* [x] --- Info.js
* [x] --- NotificationView.js
* [x] --- PhoneView.js
* [x] --- SecurityView.js
* [x] --- models
* [x] ---- geographic.ts
* [x]   Authorized.tsx
* [x]   Dashboard
* [x]   Analysis.tsx
* [x]   IntroduceRow.tsx
* [x]   Monitor.tsx
* [x]   OfflineData.tsx
* [x]   ProportionSales.tsx
* [x]   SalesCard.tsx
* [x]   TopSearch.tsx
* [x]   Workplace.tsx
* [x] --  models
* [x] ---  activities.ts
* [x] ---  chart.ts
* [x] ---  monitor.ts
* [x]   Exception
* [x] --  403.tsx
* [x] --  404.tsx
* [x] --  500.tsx
* [x] -- TriggerException.js
* [x] -- models
* [x] --- error.ts
* [x] Forms
* [x] -- AdvancedForm.js
* [x]  -- BasicForm.js
* [x]  -- StepForm
* [x]  --- Step1.js
* [x]  --- Step2.js
* [x]  --- Step3.js
* [x]  --- index.js
* [x] -- TableForm.js
* [x] -- models
* [x]  --- form.js
* [x]  List
* [x]  -- Applications.js
* [x]  -- Articles.js
* [x]  -- BasicList.js
* [x]  -- CardList.js
* [x]  -- List.js
* [x]  -- Projects.js
* [x]  -- TableList.js
* [x]  -- models
* [x]  --- rule.js
* [x]   Profile
* [x]  --AdvancedProfile.js
* [x]  -- BasicProfile.js
* [x]  -- models
* [x]  --- profile.js
* [x]  Result
* [x]  -- Error.js
* [x]  -- Success.js
* [x]  User
* [x]  -- Login.js
* [x]  -- Login.less
* [x]  --Register.js
* [x]  -- RegisterResult.js
* [x]  -- models
* [x]  --- register.js

## services
* [x]  api.ts
* [x] error.ts
* [x] geographic.ts
* [x] user.ts

* [x] utils
* [x] -- Authorized.ts
* [x] -- Yuan.tsx
* [x] -- authority.test.js
* [x] -- authority.ts
* [x] -- getPageTitle.ts
* [x] -- request.ts
* [x] -- utils.test.js
* [x] -- utils.tsx

**Comment by xiaohuoni** [comment]
# fix e2e
* [ ]  baseLayout.e2e.js
* [ ]  home.e2e.js
* [ ] login.e2e.js
* [ ]  topMenu.e2e.js
* [ ] userLayout.e2e.js

**Comment by xiaohuoni** [comment]
# umi test -ts

**Comment by xiaohuoni** [comment]
# merge to V4
https://github.com/ant-design/ant-design-pro/pull/3702

**Comment by xiaohuoni** [comment]
# commit to pro blocks
https://github.com/ant-design/pro-blocks
* [ ] AccountCenter	 
* [ ] AccountSettings	 
* [ ] AdvancedForm	 
* [ ] AdvancedProfile	 
* [ ] Analysis	 
* [ ] BasicForm	 
* [ ] BasicList	 
* [ ] BasicProfile	 
* [ ] CardList	 
* [ ] Exception403	 
* [ ] Exception404	 
* [ ] Exception500	 
* [ ] Monitor	 
* [ ] ResultFail	 
* [ ] ResultSuccess	 
* [ ] SearchListApplications	 
* [ ] SearchListArticles	 
* [ ] SearchListProjects	 
* [ ] StepForm	 
* [ ] TableList	 
* [ ] UserLogin	 
* [ ] UserRegister	 
* [ ] UserRegisterResult	 
* [ ] Workplace

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/3143

# eslint
https://github.com/ant-design/ant-design-pro/pull/3722

**Comment by crashsol** [comment]
手动点赞，要努力学习了

**Comment by imhele** [comment]
准备从之前写过的组件合并进来：
- [x] Result
- [x] DescriptionList

**Comment by wangxingkang** [comment]
@xiaohuoni 是在这个项目上持续开发吗  这个项目是我开发的 如果可以， 两个项目 可以合并 一个人维护 有点太慢 https://github.com/ts-react/react-admin-template

**Comment by xiaohuoni** [comment]
@wangxingkang 不是，这些提交是为了，pro官方的v4版本，kit这个项目存在的意义，是希望，把项目分成碎片提交，对阅读源码学习的人友好。

**Comment by wangxingkang** [comment]
类似一个组件、功能开发完毕会有一次提交记录？

**Comment by xiaohuoni** [comment]
只是我个人的一种尝试，我希望，把这个项目当作一个新手教程来组织。把常规用法提问，沉淀到，commit评论或者review里面，大概的想法。
> v3基本完成之后，以step by step的方式通过一个Issues对应一个PR的方式，同步部分代码到ant-design-kit，便于初学者阅读源码。可以在相应的Issues和PR上评论提问。持续维护答疑。当作一个公开的学习笔记。

**Comment by xiaohuoni** [comment]
截止这次提交https://github.com/ant-design/ant-design-pro/pull/3691 ，pages下面的所有文件都已转换成typescript。

**Comment by xiaohuoni** [comment]
components 直接在v4分支上面修改！后续再手动合并到v3.🤦‍♂️ 
v4 需要的部分components已完成 https://github.com/ant-design/ant-design-pro/pull/3702
剩余部分先继续在v3中进行

**Comment by xiaohuoni** [comment]
截止今天，剩余计划24项。接下来，如果无法安心下来组织kit文档。可以考虑。完成区块pro-block

**Comment by crashsol** [comment]
@xiaohuoni pro-block在umi和pro里面都有，以后会以哪个为准呢

**Comment by xiaohuoni** [comment]
@crashsol https://github.com/ant-design/pro-blocks 你好应该是这个，之前在umi里面叫做umi-blocks，后来改了个名字。

**Comment by xiaohuoni** [comment]
剩余一个Authorized
新增一个bug
* [ ] 国际化挂了
