### ISSUE TITLE
现有的几个工具js转为ts

### ISSUE THREAD

**Issue by xiaohuoni** [xiaohuoni/ant-design-kit#5]
如pro中services和utils里面的文件

**Comment by hanwenbo** [comment]
是干嘛的呢

**Comment by xiaohuoni** [comment]
额，怎么说呢，是为了写一个社区化需求的脚手架，顺便用ts重写一些pro的js，顺便学习一下ts，顺便搞一个入门教程，从iss1开始看起，可以从零搭建一个ts版本的pro@4.0。
